# Generated by Django 3.2.16 on 2023-09-21 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events_details',
            fields=[
                ('events_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('events_name', models.CharField(blank=True, max_length=250, null=True)),
                ('events_details', models.CharField(blank=True, max_length=250, null=True)),
                ('events_schedule', models.DateTimeField()),
                ('ips_url', models.CharField(blank=True, max_length=250, null=True)),
                ('events_requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
