# Generated by Django 3.2.16 on 2023-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_alter_events_details_events_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_details',
            name='events_schedule',
            field=models.DateTimeField(),
        ),
    ]
