# Generated by Django 3.2.16 on 2023-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_alter_events_details_events_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_details',
            name='event_active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
