# Generated by Django 3.2.16 on 2023-10-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_attendancemonitoring_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemonitoring',
            name='attendee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
