# Generated by Django 3.2.16 on 2023-10-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0013_userlogs_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='date_performed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
