# Generated by Django 3.2.16 on 2023-10-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0014_userlogs_date_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_details',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
