# Generated by Django 3.2.16 on 2023-10-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0017_userchangelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChangeLog',
        ),
    ]
