# Generated by Django 3.2.16 on 2023-10-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0021_eventlogs_historicaleventlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('BSIT', 'BSIT'), ('BSBA', 'BSBA'), ('BSHRM', 'BSHRM'), ('BSTM', 'BSTM'), ('BSeD', 'BSeD'), ('BSPSYC', 'BSPSYC'), ('BSPS', 'BSPS'), ('BSMT', 'BSMT')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Guest', 'Guest')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('BSIT', 'BSIT'), ('BSBA', 'BSBA'), ('BSHRM', 'BSHRM'), ('BSTM', 'BSTM'), ('BSeD', 'BSeD'), ('BSPSYC', 'BSPSYC'), ('BSPS', 'BSPS'), ('BSMT', 'BSMT')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Guest', 'Guest')], max_length=255, null=True),
        ),
    ]
