# Generated by Django 3.2.16 on 2023-10-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0022_auto_20231016_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='new_pass',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_pass',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
