# Generated by Django 3.2.16 on 2023-10-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0024_eventparticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipants',
            old_name='event_id',
            new_name='event',
        ),
    ]
