# Generated by Django 3.2.16 on 2023-10-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0025_rename_event_id_eventparticipants_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipants',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee', to='eventapp.userprofile'),
        ),
    ]
