# Generated by Django 3.2.16 on 2023-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0026_alter_eventparticipants_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipants',
            name='ev_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
