# Generated by Django 3.2.16 on 2023-10-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0027_eventparticipants_ev_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipants',
            old_name='ev_id',
            new_name='ei',
        ),
    ]
