# Generated by Django 3.2.16 on 2023-10-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0028_rename_ev_id_eventparticipants_ei'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_details',
            name='ips_online',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=7),
        ),
        migrations.AddField(
            model_name='historicalevents_details',
            name='ips_online',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=7),
        ),
    ]
