# Generated by Django 3.2.16 on 2023-11-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0029_auto_20231026_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attendee', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('date_performed', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
