# Generated by Django 3.2.16 on 2023-11-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0030_ecert'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_details',
            name='apr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents_details',
            name='apr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
