# Generated by Django 3.2.16 on 2023-11-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0031_auto_20231107_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipsurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipsurl', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
