# Generated by Django 3.2.16 on 2023-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0033_qform'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecert',
            name='avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecert',
            name='q1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecert',
            name='q2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecert',
            name='q3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecert',
            name='q4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
