# Generated by Django 3.2.16 on 2023-11-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0034_auto_20231114_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecert',
            name='q1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='ecert',
            name='q2',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='ecert',
            name='q3',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='ecert',
            name='q4',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
