# Generated by Django 3.2.16 on 2023-11-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0035_auto_20231114_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMonitoring2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.CharField(blank=True, max_length=255, null=True)),
                ('events_details_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sess_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMonitoring3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.CharField(blank=True, max_length=255, null=True)),
                ('events_details_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sess_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qform',
            name='question',
        ),
        migrations.AddField(
            model_name='qform',
            name='quest2ion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceMonitoring3',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('attendee', models.CharField(blank=True, max_length=255, null=True)),
                ('events_details_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sess_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time_in', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attendance monitoring3',
                'verbose_name_plural': 'historical attendance monitoring3s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceMonitoring2',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('attendee', models.CharField(blank=True, max_length=255, null=True)),
                ('events_details_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sess_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time_in', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attendance monitoring2',
                'verbose_name_plural': 'historical attendance monitoring2s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
