# Generated by Django 3.2.16 on 2023-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0038_auto_20231201_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='qform',
            name='q_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
