# Generated by Django 3.2.16 on 2023-12-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0039_qform_q_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='logourl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logourl', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
