# Generated by Django 3.2.16 on 2023-12-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0040_logourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_details',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='historicalevents_details',
            name='qr_code',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
