# Generated by Django 3.2.16 on 2023-12-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0041_auto_20231208_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_details',
            name='cert_allowed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalevents_details',
            name='cert_allowed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
